version: 2

common: &common
  working_directory: ~/remotepixel-tiler
  steps:
    - checkout
    - run:
        name: install dependencies
        command: pip install tox codecov pre-commit --user
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: run pre-commit
        command: |
          if [[ "$CIRCLE_JOB" == "python-3.6" ]]; then
             ~/.local/bin/pre-commit run --all-files
          fi
    - run:
        name: upload coverage report
        command: |
          if [[ "$UPLOAD_COVERAGE" == 1 ]]; then
             ~/.local/bin/coverage xml
             ~/.local/bin/codecov
          fi
        when: always


jobs:
  "python-3.6":
    <<: *common
    docker:
      - image: circleci/python:3.6.5
        environment:
          - TOXENV=py36
          - UPLOAD_COVERAGE=1

  "python-3.7":
    <<: *common
    docker:
      - image: circleci/python:3.7.2
        environment:
          - TOXENV=py37

  package:
    docker:
      - image: remotepixel/amazonlinux-gdal:2.4.0
        environment:
          - PACKAGE_PATH=package.zip
          - PACKAGE_TMP=/root/package
    working_directory: ~/remotepixel-tiler
    steps:
      - checkout
      - attach_workspace:
          at: ~/remotepixel-tiler
      - run:
          name: install requirements
          command: pip3 install . --no-binary numpy,rasterio -t $PACKAGE_TMP -U
      - run:
          name: create package
          command: bin/package.sh
      - persist_to_workspace:
          root: .
          paths:
            - package.zip

  "test-package":
    docker:
      - image: lambci/lambda:build-python3.6
    working_directory: ~/remotepixel-tiler
    steps:
      - checkout
      - run: unzip -q package.zip -d /var/task/
      - run: bin/tests.sh


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - package:
          requires:
            - "test"
      # - deploy:
      #     requires:
      #       - "package"
      #     filters:
      #       tags:
      #         only: /^[0-9]+.*/
      #       branches:
      #         ignore: /.*/
